(ns meta-flow.store.protocol)

(defprotocol StateStore
  (upsert-collection-state! [store collection-state])
  (find-collection-state [store collection-id])
  (enqueue-task! [store task])
  (find-task [store task-id])
  (find-task-by-work-key [store work-key])
  (create-run! [store task run lease])
  (claim-task-for-run! [store task run lease task-transition run-transition now])
  (recover-run-startup-failure! [store task run now])
  (find-run [store run-id])
  (find-latest-run-for-task [store task-id])
  (ingest-run-event! [store event-intent])
  (list-run-events [store run-id])
  (list-run-events-after [store run-id event-seq])
  (attach-artifact! [store run-id artifact])
  (find-artifact [store artifact-id])
  (record-assessment! [store assessment])
  (find-assessment-by-key [store run-id assessment-key])
  (record-disposition! [store disposition])
  (find-disposition-by-key [store run-id disposition-key])
  (transition-task! [store task-id transition now])
  (transition-run! [store run-id transition now]))
